### ISSUE TITLE
Shopware required version 6.4

### ISSUE THREAD

**Issue by xndrdev** [Freizeit-Koding-Klub/crator#47]
```"require": {
    "shopware/core": ">=6.4"
},```

Ist das wichtig, dass es nur ab 6.4 funzt?

**Comment by supus** [comment]
@xndrdev  Ne hatte das erstmal nur so eingebaut. Soll ich das wieder rausnehmen? Oder vllt passt das dann der jeweilige entwickler an wenn er daran arbeitet. glaube diesen monat kommt 6.4. als offizielle Version raus. glaube da wird das dann bei neuen projekten immer mindestens benutzt.

**Comment by xndrdev** [comment]
@supus Ich schlage vor es erstmal rauszunehmen, sonst koennten wir das bei den aktuellen Projekten die keine 6.4 ham noch nicht nutzen.
