### ISSUE TITLE
Route import is missing in controller file

### ISSUE THREAD

**Issue by xndrdev** [Freizeit-Koding-Klub/crator#56]
`use Shopware\Core\Framework\Routing\Annotation\RouteScope;` is correct, but the import for route is missing

**Comment by xndrdev** [comment]
`use Symfony\Component\Routing\Annotation\Route;` is the missing one

**Comment by lodric-origin** [comment]
added

<img width="610" alt="image" src="https://user-images.githubusercontent.com/57989249/114311303-83428200-9aee-11eb-97b6-4c030e241730.png">
